Feat/111 event에 club기능 일부 추가(1)
Jyoonly/nest-study-eventory pull request #15
Opened 2024-12-07 21:46 UTC by Jyoonly

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
1. 기존 event의 dto, payload, query, type등에 clubId를 추가하였습니다.
2. 모임 생성 API에 clubId가 들어가게 수정했습니다.
3. 모임 여러개 조회 API에 clubId가 들어가게 수정했습니다
  - clubId 쿼리 사용은 해당 클럽 가입자만 가능하도록 service에서 체크
  - 모든 쿼리를 비우고 조회한다면, clubId가 null인 모임에 한정해서 전체조회됨. 
  
## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-08 03:58 UTC, worjs requested changes
1개짜리 get할때도 권한체크 해주시면 좋을듯!

++ 이전 PR들 처리하면 이제 아카이브 모임이 생길텐데 그것도 고려해서 수정해주시면 되겠습니다

2024-12-08 03:58 UTC, worjs commented on src/event/dto/event-detail.dto.ts
> +  })
이것보단
`clubId!: number | null` 이면 충분하지 않을까요ㅎㅎ

2024-12-08 03:58 UTC, worjs commented on src/event/event.repository.ts
> +    }
사실은 쿼리 스트링이라는게 비워져서 오면 해당 조건 없이 전체조회되는게 기대(?) 되거든요.
말씀하신대로 하려면 clubId = null 로 쿼리 스트링을 입력해야 되구요.

그냥 기존처럼 쿼리 스트링은 있으면 조건절에 넣는 식으로 하면 될 것 같습니다.

2024-12-08 14:53 UTC, Jyoonly commented
1개짜리 get은 다른 브랜치로 작업 중입니다!  isArchived도 일단 다음 브랜치에서 작업해보고 있습니다. 
쿼리스트링에 대해서는 일단 바꿔보긴 했는데 이렇게 바꾸는게 맞을까요?

2024-12-08 15:01 UTC, worjs requested changes

2024-12-08 15:01 UTC, worjs commented on src/event/event.service.ts
> +    }
음 clubId의 유효성을 확인할 필요는 없습니다!
다른 query 값들도 유효성을 확인하고 있지는 않기도 하고, 그 이유는 PPT나 수업에서도 다룬거 같아서 생략하겠습니다.

여기서 중요한건,
clubId를 필터링 값으로 안주더라도, 내가 가입한 클럽이 아니면 조회할 수 없어야 합니다.

예를 들어서 clubId에 값을 안주었다고 합시다.
그러면 query.clubId는 없으니, getEvents(query)로 가져온 모임들 중에는 내가 가입한 클럽의 모임도 있을거고, 아닌 모임들도 있죠.

여기서 그 모임들 중에서, 내가 가입한 클럽 모임은 보여야하고, 내가 가입하지 않은 클럽 모임은 빠져야하고, 일반 모임들은 보여야 합니다. 그 필터링 과정이 포함되어야 합니다!

2024-12-08 15:01 UTC, worjs commented on src/event/event.service.ts
> +    }
결국은 유저별로 조회 권한을 확인해서 볼 수 없는 것들은 제거하고 내려보내는 과정이라고 보시면 되겠습니다.

2024-12-08 16:27 UTC, Jyoonly commented
레포지토리 단계에서 필터링 방식 수정해보고, 서비스 단계에서의 유효성 확인은 모두 제거했습니다..!! 현재 필터링 방식 괜찮을까요?

2024-12-09 02:36 UTC, worjs approved these changes

2024-12-09 02:36 UTC, worjs commented on src/event/event.repository.ts
> +        ],
저는 이 권한 관련 부분까지 쿼리에 넣어버리면 오히려 쿼리가 너무 복잡해져서, 보통 일단 다 가져온 다음에 서비스에서 작업하는 편이예요.

복잡한 조회 쿼리는 결국 DB에도 많은 부담을 주게 되어서, 서비스가 성장하면 빠르게 병목이 되거든요.
근데 그 경우에는 또 캐싱이나 인덱스를 활용해서 부담을 덜게 할 수도 있기도 해서, 꼭 바꾸라고 말씀드리기는 힘들 것 같네요!

아무튼 
- 복잡한 쿼리는 DB에 안좋고 나중에 부하가 커질 수 있음.
- 어떤 조회는 DB(2차 저장소)보단 서버 메모리(1차 저장소)에서 처리하는게 나을 수도 있음. 

정도만 알아두고 지나가기로 합시다!

2024-12-09 06:07 UTC, Jyoonly commented on src/event/event.repository.ts
> +        ],
사실 저도 레포지토리쪽 함수가 너무 복잡해지는것 같아서 고민되었는데 다음엔 그런 방식을 적용해봐야겠어요! 감사합니다.

말씀하신 방식은 기본적인 쿼리 기반으로 일단 제한 없이 getEvents를 통해 데이터를 싹 가져온 후, 서비스 계층에서 필터링을 진행한다는 게 맞을까요? 이때 필터링은 레포지토리에 필터링 함수(ex. filterClubNotJoined: 속하지 않은 클럽 모임 제외, filterArchivedNotJoined: 참여하지 않은 아카이브 모임 제외)를 만들고 서비스에서 호출해서 권한 없는 데이터는 제거해나가는 방식으로 진행하면 될까요? 제대로 이해했는지 확인하고 싶어 질문드립니다..!

2024-12-09 06:45 UTC, worjs commented on src/event/event.repository.ts
> +        ],
옙 정확하게 이해해주셨습니다~
저도 좀 더 설명을 잘 드리고 싶었는데, 정신이 없다보니 쉽지 않네요ㅋㅋㅋ
아무튼 완전 정확합니당

2024-12-09 06:50 UTC, Jyoonly commented on src/event/event.repository.ts
> +        ],
설명 너무 잘해주셨는걸요! 덕분에 확실히 이해됐습니다 감사합니다ㅎㅎ

2024-12-09 06:50 UTC, merged