Feat/112 모임 상세 조회, 모임 수정, 모임 참여에 clubId, isArchived 반영
Jyoonly/nest-study-eventory pull request #18
Opened 2024-12-08 15:41 UTC by Jyoonly

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
모임 상세 조회, 모임 수정, 모임 참여에 clubId, isArchived 반영하였습니다.  

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-08 16:01 UTC, worjs requested changes

2024-12-08 16:01 UTC, worjs commented on src/event/event.service.ts
> +    const isEventArchived = await this.eventRepository.isEventArchived(eventId);
이정도는 findEventDetailById 여기에서 같이 조회해와도 좋을 것 같습니다

2024-12-08 16:01 UTC, worjs commented on src/event/event.service.ts
> +      throw new ConflictException('아카이브된 이벤트는 수정할 수 없습니다.');
음 아카이브된 모임은 시작시간이 지난 모임들이라 원래 수정 불가!
이 코드는 없어도 될 것 같아요

2024-12-08 16:34 UTC, Jyoonly commented
밤늦게까지 리뷰 주셔서 너무 감사합니다! 리뷰 바탕으로 수정해보았습니다.

2024-12-09 02:04 UTC, worjs approved these changes
굿!!

2024-12-09 06:55 UTC, merged